server:
  port: 10100

eureka:
  instance:
#    服务器域名
    hostname: localhost
  client:
#    当前是服务提供方，需要注册到Eureka
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/